version: '3.3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - /home/alec/hack-reactor/docker-volumes:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: <PASSWORD>
      POSTGRES_USER: <USER>
      POSTGRES_DB: stashit

  app:
    image: alecchampaign/stashit:1.0
    restart: always
    depends_on:
      - db
    ports:
      - 4000:4000
    environment:
      DB_PASS: <PASSWORD>
      DB_USER: <USER>
